# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1
[ja]
languageName = "Japanese"
languagedirection = "ltr"
title = "Example Site"
weight = 1